apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    app: blue
spec:
  selector:
    matchLabels:
      app: blue
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
        - name: blue
          image: 'aballen/blue:1.1'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 100m
              cpu: '0.5'
            limits:
              memory: 300m
              cpu: '1'
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              path: /index.html
              port: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
  labels:
    app: green
spec:
  selector:
    matchLabels:
      app: green
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
        - name: green
          image: 'aballen/green:1.1'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 100m
              cpu: '0.5'
            limits:
              memory: 300m
              cpu: '1'
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              path: /index.html
              port: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 5            
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary
  labels:
    app: canary
spec:
  selector:
    matchLabels:
      app: canary
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
        - name: canary
          image: 'aballen/canary:1.1'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 100m
              cpu: '0.5'
            limits:
              memory: 300m
              cpu: '1'
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              path: /index.html
              port: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 5