apiVersion: v1
kind: Pod
metadata:
  name: blue
spec:
  containers:
  - name: blue
    image: aballen/blue
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: green
spec:
  containers:
  - name: green
    image: aballen/blue
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: canary
spec:
  containers:
  - name: canary
    image: aballen/canary
    ports:
    - containerPort: 80
